export const getGenres = (): string[] => {
  return [
    "+18",
    "Action",
    "Adventure",
    "Apocalips",
    "Comedy",
    "Crime",
    "Detective",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Gore",
    "Harem",
    "Historical",
    "Horror",
    "Isekai",
    "Magic",
    "Martial Arts",
    "Mecha",
    "Mystery",
    "Post-Apocalyptic",
    "Psychological",
    "Rencarnation",
    "Romance",
    "School Life",
    "Sci-Fi",
    "Slice of Life",
    "Sports",
    "Supernatural",
    "Superpowers",
    "Survival",
    "Thriller",
    "Tragedy",
    "Vanila",
    "Yaoi",
    "Yuri",
  ];
};
